# Generated by Django 4.2.25 on 2025-10-04 22:13

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.core.models.ordering
import nautobot.extras.models.mixins
import nautobot.extras.models.roles
import nautobot.extras.models.statuses
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
        ('tenancy', '0009_update_all_charfields_max_length_to_255'),
        ('dcim', '0074_alter_rack_u_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransceiverType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('model', models.CharField(max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('form_factor', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('speed', models.PositiveSmallIntegerField()),
                ('medium', models.CharField(max_length=10)),
                ('lane_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('actual_reach', models.PositiveIntegerField(blank=True, null=True)),
                ('power_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transceiver_types', to='dcim.manufacturer')),
                ('module_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transceiver_types', to='dcim.modulefamily')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('manufacturer', 'model'),
                'unique_together': {('manufacturer', 'model')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransceiverPortTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('_name', nautobot.core.models.fields.NaturalOrderingField('name', blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('required_form_factor', models.CharField(blank=True, max_length=50)),
                ('device_type', nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.devicetype')),
                ('module_type', nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.moduletype')),
                ('transceiver_family', nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transceiver_port_templates', to='dcim.modulefamily')),
            ],
            options={
                'ordering': ('device_type', 'module_type', '_name'),
                'abstract': False,
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransceiverPort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('required_form_factor', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('_name', nautobot.core.models.fields.NaturalOrderingField('name', blank=True, db_index=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('parent_device', nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transceiver_ports', to='dcim.device')),
                ('parent_module', nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transceiver_ports', to='dcim.module')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('transceiver_family', nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transceiver_ports', to='dcim.modulefamily')),
            ],
            options={
                'ordering': ('parent_device', 'parent_module__id', '_name'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Transceiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('serial', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transceivers', to='dcim.location')),
                ('parent_transceiver_port', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_transceiver', to='dcim.transceiverport')),
                ('role', nautobot.extras.models.roles.RoleField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.role')),
                ('status', nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transceivers', to='tenancy.tenant')),
                ('transceiver_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transceivers', to='dcim.transceivertype')),
            ],
            options={
                'ordering': ('parent_transceiver_port', 'transceiver_type', 'asset_tag', 'serial'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='transceiverporttemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='dcim_transceiverporttemplate_device_type_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='transceiverporttemplate',
            constraint=models.UniqueConstraint(fields=('module_type', 'name'), name='dcim_transceiverporttemplate_module_type_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='transceiverport',
            constraint=models.UniqueConstraint(fields=('parent_device', 'name'), name='dcim_transceiverport_parent_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='transceiverport',
            constraint=models.UniqueConstraint(fields=('parent_module', 'name'), name='dcim_transceiverport_parent_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='transceiver',
            constraint=models.UniqueConstraint(fields=('transceiver_type', 'serial'), name='dcim_transceiver_transceiver_type_serial_unique'),
        ),
    ]
