# Generated by Django 4.2.25 on 2025-10-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_transceivertype_transceiverporttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transceivertype',
            name='speed',
            field=models.PositiveIntegerField(),
        ),
    ]
