# Generated by Django 4.2.25 on 2025-10-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0076_alter_transceivertype_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transceiverport',
            name='transceiver_family',
        ),
        migrations.RemoveField(
            model_name='transceiverporttemplate',
            name='transceiver_family',
        ),
    ]
