# Generated by Django 4.2.25 on 2025-10-05 17:07

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.core.models.ordering
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
        ('dcim', '0077_remove_transceiverport_transceiver_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransceiverBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('required_form_factor', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('_name', nautobot.core.models.fields.NaturalOrderingField('name', blank=True, db_index=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('parent_device', 'parent_module__id', '_name'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='TransceiverPortTemplate',
            new_name='TransceiverBayTemplate',
        ),
        migrations.RemoveField(
            model_name='transceiverport',
            name='parent_device',
        ),
        migrations.RemoveField(
            model_name='transceiverport',
            name='parent_module',
        ),
        migrations.RemoveField(
            model_name='transceiverport',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='transceiver',
            options={'ordering': ('parent_transceiver_bay', 'transceiver_type', 'asset_tag', 'serial')},
        ),
        migrations.RemoveConstraint(
            model_name='transceiverbaytemplate',
            name='dcim_transceiverporttemplate_device_type_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='transceiverbaytemplate',
            name='dcim_transceiverporttemplate_module_type_name_unique',
        ),
        migrations.RemoveField(
            model_name='transceiver',
            name='parent_transceiver_port',
        ),
        migrations.AddConstraint(
            model_name='transceiverbaytemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='dcim_transceiverbaytemplate_device_type_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='transceiverbaytemplate',
            constraint=models.UniqueConstraint(fields=('module_type', 'name'), name='dcim_transceiverbaytemplate_module_type_name_unique'),
        ),
        migrations.DeleteModel(
            name='TransceiverPort',
        ),
        migrations.AddField(
            model_name='transceiverbay',
            name='parent_device',
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transceiver_bays', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='transceiverbay',
            name='parent_module',
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transceiver_bays', to='dcim.module'),
        ),
        migrations.AddField(
            model_name='transceiverbay',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='transceiver',
            name='parent_transceiver_bay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_transceiver', to='dcim.transceiverbay'),
        ),
        migrations.AddConstraint(
            model_name='transceiverbay',
            constraint=models.UniqueConstraint(fields=('parent_device', 'name'), name='dcim_transceiverbay_parent_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='transceiverbay',
            constraint=models.UniqueConstraint(fields=('parent_module', 'name'), name='dcim_transceiverbay_parent_module_name_unique'),
        ),
    ]
